name: dart_grpc_example
description: A sample command-line application.
version: 1.0.3
# homepage: https://www.example.com

environment:
  sdk: "^3.0.0"

dependencies:
  protobuf: ^4.1.1
  grpc: ^4.1.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
