name: grpc-gen-ts

# This workflow builds and pushes the grpc-gen-python Docker image
# and generates the Python example code.
# It is triggered on pushes to the main branch that affect the grpc-gen-python directory.

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - grpc-gen-ts/**/*

jobs:
  build-grpc-gen-ts:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build image
        run: make -C grpc-gen-ts build

      - name: Push image
        run: make -C grpc-gen-ts push

      - name: Build ts example
        run: make -C grpc-gen-ts generate-example
