name: grpc-gen-python
permissions:
  contents: read

on:
    branches:
      - main
    paths:
      - grpc-gen-python/**/*
jobs:
  build-grpc-gen-python:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build image
        run: make -C grpc-gen-python build

      - name: Push image
        run: make -C grpc-gen-python push

      - name: Build python example
        run: make -C grpc-gen-python generate-example
