name: grpc-gen-dart

# This workflow builds and pushes the grpc-gen-dart Docker image
# and generates the Dart example code.
# It is triggered on pushes to the main branch that affect the grpc-gen-dart directory.

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - grpc-gen-dart/**/*

jobs:
  build-grpc-gen-dart:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build image
        run: make -C grpc-gen-dart build

      - name: Push image
        run: make -C grpc-gen-dart push

      - name: Build dart example
        run: make -C grpc-gen-dart generate-example
